-- TABLA DE PROYECTOS (CRONOGRAMA)
-- Ejecuta este script en el SQL Editor de Supabase para habilitar el guardado de briefs en la nube.

-- 1. Crear la tabla `projects`
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Campos del Proyecto
    title TEXT NOT NULL,
    description TEXT,
    reason TEXT,             -- Usado para guardar Objetivo/Titular/Refs del brief
    image_url TEXT,
    due_date TEXT,           -- Guardamos fecha como string 'YYYY-MM-DD' para consistencia con JSON actual
    status TEXT DEFAULT 'pending', 
    
    -- Relación con Cliente
    nit TEXT NOT NULL,       -- Identificador del cliente (ej: '901329423')
    client_name TEXT         -- Nombre opcional para referencia rápida
);

-- 2. Habilitar seguridad (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acceso
-- Permitir que CUALQUIERA lea los proyectos (necesario para que la web los muestre)
-- Nota: En un futuro podrías querer restringir esto, pero para empezar así es más fácil.
CREATE POLICY "Public Read Access"
ON public.projects
FOR SELECT
USING (true);

-- Permitir que CUALQUIERA inserte proyectos (para el formulario de Brief)
CREATE POLICY "Public Insert Access"
ON public.projects
FOR INSERT
WITH CHECK (true);

-- Comentario
COMMENT ON TABLE public.projects IS 'Almacena los items del cronograma generados desde la web.';
