-- Esquema SQL para la tabla de respuestas de la encuesta en Supabase.
-- Puedes ejecutar este código en el "SQL Editor" de tu proyecto de Supabase.

-- 1. Creación de la tabla `survey_responses`
CREATE TABLE public.survey_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

    -- Sección 1: Información Básica
    q1_name TEXT,
    q1_location TEXT,
    q1_country TEXT,
    q1_phone TEXT,
    q1_experience INT,
    q1_role TEXT[], -- Array para selección múltiple
    q1_role_other TEXT,

    -- Sección 2: Oferta de Servicios
    q2_services TEXT[], -- Array para selección múltiple
    q2_other TEXT,
    q2_unique TEXT,

    -- Sección 2: Identidad y Valores
    q3_persona TEXT,
    q4_perception TEXT[], -- Array para selección múltiple
    q4_other TEXT,
    q5_emotions TEXT[], -- Array para selección múltiple
    q5_other TEXT,
    q6_why TEXT,

    -- Sección 3: Diferenciación y Valor
    q7_differentiation TEXT[], -- Array para selección múltiple
    q7_other TEXT,
    q7_why TEXT,
    q8_value TEXT[], -- Array para selección múltiple
    q8_other TEXT,

    -- Sección 4: Presencia Online y Marketing
    q9_presence TEXT[], -- Array para selección múltiple
    q9_other TEXT,
    q10_rating INT,
    q10_challenges TEXT[], -- Array para selección múltiple
    q10_other TEXT,

    -- Sección 5: Visión a Futuro y Preferencias
    q11_training TEXT,
    q12_details TEXT,
    q13_colors TEXT[], -- Array para selección múltiple
    q13_other TEXT,
    q14_hobby TEXT,

    -- Reflexión Final y Competidores
    q15_final TEXT,
    competitors TEXT[] -- Array para los nombres de los competidores
);

-- 2. Habilitar Row Level Security (RLS) en la tabla
-- ¡MUY IMPORTANTE para la seguridad de tus datos!
ALTER TABLE public.survey_responses ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas de seguridad para la tabla
-- Esta política permite a cualquier persona (anon) insertar una nueva respuesta en la encuesta.
CREATE POLICY "Allow public insert"
ON public.survey_responses
FOR INSERT
WITH CHECK (true);

-- Esta política deniega por defecto la lectura (SELECT), actualización (UPDATE) o eliminación (DELETE)
-- a usuarios anónimos. Solo el rol `service_role` (usado desde el servidor) o políticas específicas
-- que crees para usuarios autenticados podrán acceder a los datos.
-- No necesitas una política explícita de DENY ALL, ya que RLS es denegación por defecto.

-- Comentario sobre el uso:
COMMENT ON TABLE public.survey_responses IS 'Almacena las respuestas del formulario de diagnóstico estratégico para el sector salud y general.';
